inherit_gem:
  prawn-dev: rubocop.yml

RSpec/FilePath:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 7
  Exclude:
    - spec/ttfunk/table/os2_spec.rb

Style/FormatStringToken:
  Exclude:
    - examples/metrics.rb
