inherit_gem:
  prawn-dev: rubocop.yml

RSpec/FilePath:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 7
  Exclude:
    - spec/ttfunk/table/os2_spec.rb

RSpec/SpecFilePathFormat:
  CustomTransform:
    TTFunk: ttfunk
  Exclude:
    - spec/ttfunk/table/cff/charstrings_index_spec.rb
    - spec/ttfunk/table/cff/name_index_spec.rb

Style/FormatStringToken:
  Exclude:
    - examples/metrics.rb


Style/Documentation:
  Exclude:
    - examples/**/*.rb
    - spec/**/*.rb
