
# Possibly won't remove due to intentional style decisions
SignalException:
  Enabled: false
CaseIndentation:
  Enabled: false
IfUnlessModifier:
  Enabled: false
StringLiterals:
  Enabled: false


Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Max: 6
Metrics/PerceivedComplexity:
  Enabled: false


Style/Documentation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/NumericPredicate:
  EnforcedStyle: comparison
